---
  - hosts: laptops
    become: true
    vars:
      rpmfusion_key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-8"
      rpmfusion_repo: "https://download1.rpmfusion.org/free/el/updates/8/x86_64/"

    tasks:
    - name: import_rpmfusion_free_key
      ansible.builtin.rpm_key:
        key: "{{ rpmfusion_key }}"
        state: present

    - name: "install_rpmfusion_free_repo"
      ansible.builtin.yum_repository:
        name: "rpmfusion-free-release"
        description: "rpmfusion-free repo "
        baseurl: "{{ rpmfusion_repo }}"
        state: present

    - name: install_vlc
      yum:
        name: vlc
        state: present