---
  - hosts: laptops
    become: true
    tasks:
    - name: Add Sublime repository
      yum_repository:
        name: sublime-text
        description: Sublime Text x86_64 - stable
        baseurl: https://download.sublimetext.com/rpm/stable/x86_64
        enabled: yes
        gpgcheck: yes
    - name: Add Sublime Text
      yum:
        name: sublime-text
        state: present
