- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      yum:
        update_cache: yes
      changed_when: False

 tasks:
  - include: tasks/package.yml
  - include: tasks/users.yml
  - include: tasks/cron.yml
 
